
EXE:=./BUILDTEST/$(input)
SRC:=./TEST/$(input).cbl
ARGS:=-x -I ./LIB -I ./LIBT
MOD:=./BUILDTEST/$(input).so
ARGSM:=-m -I ./LIB -I ./LIBT


$(EXE): $(SRC)
	@clear
	@cobc $(ARGS) -o $(EXE) $(SRC)

module:
	@cobc $(ARGSM) -o $(MOD) $(SRC)

compile:
	@cobc $(ARGS) -o $(EXE) $(SRC)

clean:
	@rm $(EXE)

run:
	@$(EXE)
	@echo

clrscr:
	@clear
	@echo "------------------------------------------------------------------"
	@echo "-- Testing Apps / Cobol                     2025 / Julián Vidal --"
	@echo "------------------------------------------------------------------"

all: clrscr clean compile run 

