
EXE:=./BUILD/DEBUG/$(input)
SRC:=./SRC/TEST/$(input).cbl
ARGS:=-v -x -I ./SRC/LIB -I ./SRC/LIBT

MOD:=./BUILD/DEBUG/$(input).so
SRCM:=./SRC/MODULES/$(input).cbl
ARGSM:=-v -m -I ./SRC/LIB -I ./SRC/LIBT


$(EXE): $(SRC)
	@clear
	@cobc $(ARGS) -o $(EXE) $(SRC)

module:
	@cobc $(ARGSM) -o $(MOD) $(SRCM)

compile:
	@cobc $(ARGS) -o $(EXE) $(SRC) 

clean:
	@rm $(EXE)

run:
	@$(EXE)
	@echo

clrscr:
	@clear
	@echo "------------------------------------------------------------------"
	@echo "-- Testing Apps / Cobol                     2025 / Julián Vidal --"
	@echo "------------------------------------------------------------------"

all: clrscr clean compile run 

