
EXE:=./BUILD/DEBUG/$(input)
SRC:=./TEST/APPS/$(input).cbl
ARGS:=-v -x -Wothers -I ./TEST/CODE -I ./TEST/APPS/LIB -I ./TEST/APPS/SCREEN

$(EXE):$(SRC)
	@cobc $(ARGS) -o $(EXE) $(SRC) 

clean:
	@rm $(EXE)

run:
	@$(EXE)
	@echo
